spring:
  application:
    name: AUTH-SERVICE

# DB properties - start
  datasource:
    username: postgres
    password: smpostgres
    url: jdbc:postgresql://localhost:5432/sharecare_auth_db

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# DB properties - end

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka

# JWT properties - start
jwt:
  secret: oeDqIxwilT62HLEmsQYvBUU36XNlY18yg_UnKZDvsmU
# JWT properties - end