spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**,/users/**

            - id: campaign-service
              uri: lb://CAMPAIGN-SERVICE
              predicates:
                - Path=/campaigns/**

            - id: donation-service
              uri: lb://DONATION-SERVICE
              predicates:
                - Path=/donation/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# JWT properties - start
jwt:
  secret: oeDqIxwilT62HLEmsQYvBUU36XNlY18yg_UnKZDvsmU
# JWT properties - end
