package com.suman.sharecare.auth.enums;

public enum ErrorCode {
    UNKNOWN_AUTH_ERROR,
    VALIDATION_ERROR,
    USERNAME_ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,
    EMAIL_NOT_VERIFIED,
    EMAIL_ALREADY_VERIFIED,
    EMAIL_VERIFICATION_LINK_INVALID,
    BAD_CREDENTIALS,
    SESSION_EXPIRED,
    PASSWORD_RESET_LINK_INVALID,
    RESOURCE_NOT_FOUND,
    UNKNOWN_ERROR
}
