spring:
  application:
    name: DONATION-SERVICE

# DB properties - start
  datasource:
    username: postgres
    password: smpostgres
    url: jdbc:postgresql://localhost:5432/sharecare_donation_db

  jpa:
    hibernate:
      ddl-auto: update
# DB properties - end

server:
  port: 8083

# Eureka client properties - start
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    # Eureka client properties - end

# Razorpay properties - start
razorpay:
  key-id: ${RAZORPAY_KEY_ID}
  key-secret: ${RAZORPAY_KEY_SECRET}
# Razorpay properties - end